apiVersion: v1
kind: Pod
metadata:
  name: kubtrainingpod
  labels:
    app: trainingapi
spec:
  containers:
  - name: trainingctr
    image: komaljain14/image-resolver-api
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  